name: codebarr
services:
  codebarr:
    image: ghcr.io/drewstopherlee/codebarr:latest
    container_name: codebarr
    ports:
      - 5083:5083
    env_file:
      - .env
    restart: unless-stopped
